package com.afterlight.madeproject.ui

object Routes {
    const val Splash = "splash"
    const val Onboarding = "onboarding"
    const val Auth = "auth"
    const val ProfileSetup = "profile_setup"
    const val RoleSelect = "role_select"
    const val Main = "main"
    const val Home = "home"
    const val Discover = "discover"
    const val MyEvents = "my_events"
    const val Notifications = "notifications"
    const val Settings = "settings"
    const val AiSettings = "ai_settings"
    const val Accounts = "accounts"
    const val ScanRsvp = "scan_rsvp"
    const val PosterScan = "poster_scan"
    const val PaymentCheckout = "payment_checkout/{eventId}"
    const val CheckIn = "check_in/{eventId}"
    const val EventDetail = "event_detail/{eventId}"
    const val HostEvent = "host_event"
    const val HostControls = "host_controls/{eventId}"
    const val RecapWall = "recap_wall/{eventId}"

    fun eventDetail(eventId: String) = "event_detail/$eventId"
    fun paymentCheckout(eventId: String) = "payment_checkout/$eventId"
    fun checkIn(eventId: String) = "check_in/$eventId"
    fun hostControls(eventId: String) = "host_controls/$eventId"
    fun recapWall(eventId: String) = "recap_wall/$eventId"
}
